# fly.toml file generated for snake-web on 2022-05-18T17:50:32+02:00

app = "snake-web"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "./infra/docker-app/Dockerfile"

[env]
  PORT = "8080"
  URL_HOST = "snake-web.fly.dev"
  DATABASE_IPV6 = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
